# Generated by Django 5.0.4 on 2024-04-18 14:53

import autoslug.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import tinymce.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Project Name')),
                ('short_description', models.CharField(max_length=1000, verbose_name='Project Description')),
                ('long_description', tinymce.models.HTMLField()),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(default='', max_length=200, verbose_name='Project Tags'), default=list, size=None)),
                ('difficulty', models.CharField(choices=[('0', 'beginner'), ('1', 'intermediate'), ('2', 'advanced')], max_length=1, verbose_name='Project Difficulty')),
                ('project_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('enrolled_profiles', models.ManyToManyField(blank=True, related_name='enrolled_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_created', '-date_updated'),
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500, verbose_name='Solution Name')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('repo_link', models.URLField(max_length=500, verbose_name='Solution Repository')),
                ('live_link', models.URLField(blank=True, max_length=500, null=True, verbose_name=':ive Solution')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='projects.project')),
            ],
            options={
                'ordering': ('-date_created', '-date_updated'),
            },
        ),
    ]
