# Generated by Django 5.0.4 on 2024-04-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='live_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='live Solution'),
        ),
    ]
