# Generated by Django 5.0.4 on 2024-04-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_solution_live_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='enrolled_profiles',
            new_name='enrolled_users',
        ),
    ]
